FROM maven:3.8.5-openjdk-17-slim

WORKDIR /app

COPY distribuidos/ /app/distribuidos

WORKDIR /app/distribuidos

RUN mvn compile

RUN mvn dependency:copy-dependencies

WORKDIR /app/distribuidos/target/classes

ENTRYPOINT ["java", "-cp", ".:../dependency/*", "com.puj.Programa"]

CMD []
