services:
  facultad:
    image: distribuidos/facultad
    build:
      context: ./proyectoDistribuidos2025
    networks:
      - mynetwork
    command: ["A", "1", "10.150.102.169", "1081"]

  programas:
    image: distribuidos/programa-academico
    build:
      context: ./proyectoDistribuidos2025
    networks:
      - mynetwork
    command: ["a", "1", "A", "2", "2", "1081"]

  central:
    image: distribuidos/programa-academico
    build:
      context: ./proyectoDistribuidos2025
    networks:
      - mynetwork
    command: ["a", "1", "A", "2", "2", "1081"]

  mongo:
    image: distribuidos/programa-bd
    build:
      context: ./proyectoDistribuidos2025
    networks:
      - mynetwork
    command: ["a", "1", "A", "2", "2", "1081"]

networks:
  mynetwork:
    driver: bridge
