FROM maven:3.8.5-openjdk-17-slim

WORKDIR /app
COPY distribuidos/pom.xml /app/pom.xml
COPY distribuidos/src /app/src

RUN mvn compile
RUN mvn dependency:copy-dependencies

WORKDIR /app/target/classes
CMD ["java", "-cp", ".:../dependency/*", "com.puj.servidores.central"]

