FROM maven:3.8.5-openjdk-17-slim

WORKDIR /app
COPY distribuidos/pom.xml /app/pom.xml
COPY distribuidos/src /app/src

RUN mvn clean package -DskipTests
RUN mvn dependency:copy-dependencies

WORKDIR /app/target/classes

# Permitir paso de argumentos desde docker-compose con CMD
ENTRYPOINT ["java", "-cp", ".:../dependency/*", "com.puj.servidores.replica"]
