services:
  central:
    image: distribuidos/central
    build:
      context: .
      dockerfile: dockerfile-central
    networks:
      - mynetwork
    command: ["20", "10", "backup"]

  Backup:
    image: distribuidos/replica
    build:
      context: .
      dockerfile: dockerfile-replica
    networks:
      - mynetwork
    command: ["central", "10000"]

  facultad:
    image: distribuidos/facultad
    build:
      context: .
      dockerfile: dockerfile-facultad
    networks:
      - mynetwork
    command: ["Ingeniería", "2025-1", "central", "1081", "backup"]

  programas:
    image: distribuidos/programas
    build:
      context: .
      dockerfile: dockerfile-programa
    networks:
      - mynetwork
    command: ["Ingeniería de Sistemas", "2025-1", "Ingeniería", "3", "2", "facultad:1081"]
    
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
