services:
  replica:
    build:
      context: .
      dockerfile: dockerfile-replica
    image: distribuidos/replica
    networks:
      - mynetwork
    depends_on:
      - postgres
    command: ["broker", "15000"]  # <--- parámetros requeridos por replica.java
    environment:
      - PRIMARY_IP=central
      - DB_URL=jdbc:postgresql://postgres:5432/aulas

  broker:
    build:
      context: .
      dockerfile: dockerfile-broker
    image: distribuidos/broker
    networks:
      - mynetwork
    ports:
      - "5555:5555"
      - "5556:5556"

  facultad:
    build:
      context: .
      dockerfile: dockerfile-facultad
    image: distribuidos/facultad
    networks:
      - mynetwork
    command: ["Ingeniería", "2025-2", "broker", "5555", "broker"]
    depends_on:
      - broker

  academico:
    build:
      context: .
      dockerfile: dockerfile-programa
    image: distribuidos/programa-academico
    depends_on:
      - facultad
    networks:
      - mynetwork
    command: ["Sistemas", "2025-2", "Ingeniería", "3", "2", "facultad:5555"]

  centralworker1:
    build:
      context: .
      dockerfile: dockerfile-worker
    image: distribuidos/worker
    networks:
      - mynetwork
    command: ["10", "5"]
    depends_on:
      - broker

  centralworker2:
    build:
      context: .
      dockerfile: dockerfile-worker
    image: distribuidos/worker
    networks:
      - mynetwork
    command: ["10", "5"]
    depends_on:
      - broker

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: aulas
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  pgdata:

networks:
  mynetwork:
    driver: bridge
