services:
  facultad:
    image: distribuidos/facultad
    build:
      context: ./distribuidos/src/main/java/com/puj/Facultad.java
    networks:
      - mynetwork
    command: ["A", "1", "10.150.102.169", "1081"]

  academico:
    image: distribuidos/programa-academico
    build:
      context: ./distribuidos/src/main/java/com/puj/Programa.java
    depends_on:
      - facultad
    networks:
      - mynetwork
    command: ["a", "1", "A", "2", "2", "1081"]

networks:
  mynetwork:
    driver: bridge
